### ISSUE TITLE
wall/fence near woodchip facing field

### ISSUE THREAD

**Issue by JohnMcLear** [JohnMcLear/house#19]
That is right. Unless you have actually done things with the land, such as fenced and occupied it without permission, and which amount to 'adverse possession' in law, you will have no rights to it at all. Even if you are in adverse possession then the true owner could have you removed from the land if they take action before the relevant period has ended. The relevant period is laid down in the Limitation Act 1980 and is never less than 12 years, but can be longer.

http://www.landregistry.gov.uk/public/guides/public-guide-16

**Comment by JohnMcLear** [comment]
13.3M long

**Comment by Lydzi28** [comment]
https://www.jacksons-fencing.co.uk/fencing/agricultural-fencing/chain-mesh/agricultural-fencing-chain-mesh.aspx

**Comment by JohnMcLear** [comment]
4x https://www.jacksons-fencing.co.uk/product/sc_135000/3.60m-long-100mm-face-machine-rounded-half-round-rail-jakcured.aspx?tpc=AR&fmc=CW&fnc=AX&timber=0
5x https://www.jacksons-fencing.co.uk/product/sc_150110/1.80m-long-125mm-face-machine-round-half-round-fencing-stake-jakcured.aspx?tpc=AR&fmc=CW&fnc=AX&timber=0
1x https://www.jacksons-fencing.co.uk/product/sc_300100/0.90m-high-50x2.50mm-25m-roll-galvanized-chain-link-inc-line-wire.aspx?tpc=AR&fmc=CW&fnc=AX&timber=0

We suggest you use galvanised barbed staples 30mm x 3.15mm which would require 3kg per 200m & 100mm galvanised nails 4kg. galvanised ring clips - sufficient for 200m.

**Comment by JohnMcLear** [comment]
£500 of bits ordered
