### ISSUE TITLE
Wax / Oil garden furniture

### ISSUE THREAD

**Issue by JohnMcLear** [JohnMcLear/house#85]
Don't use creosote

**Comment by Lydzi28** [comment]
Chis and Siobhan used Ronseal perfect finish furniture oil (natural). Comes with a sponge pad.

**Comment by JohnMcLear** [comment]
https://www.amazon.co.uk/Ronseal-HWFSRT50-Hardwood-FurnIture-Stain/dp/B0055BLFXA/ref=sr_1_3?s=outdoors&rps=1&ie=UTF8&qid=1472472327&sr=1-3&keywords=furniture+oil+teak

**Comment by Lydzi28** [comment]
All furniture has been done now. 
The table and benches need an extra coat this spring/summer

**Comment by Lydzi28** [comment]
Table top and bench tops have had one coat this summer. Still need to do the legs and the chairs.
